# 基本语法
#server:
#  port: 8081
#
#person:
#    lastName: zx
#    age: 23
#    boss: false
#    birth: 2020/02/02
#    maps: {k1: v1, k2: v2}
#    lists:
#      - zf
#      - tyr
#      - cx
#    dog:
#      name: yz
#      age: 2